#*******************************************************************************
# Copyright (C) 2021-2022 AIR Institute
# 
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
# 
# SPDX-License-Identifier: EPL-2.0
# 
# Contributors:
#    avraampiperidis- initial API and implementation
#*******************************************************************************

# This is a kubernetes configuration file describing
# how we want to have a gitlab-runner deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab-runner-deployment
  labels:
    app: gitlab-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitlab-runner
  template:
    metadata:
      labels:
        app: gitlab-runner
    spec:
      containers:
        - name: gitlab-runner
          image: gitlab/gitlab-runner:alpine          
          volumeMounts:
            - mountPath: /etc/gitlab-runner
              name: gitlab-volume
              subPath: gitlab-runner
            - mountPath: /certs
              name: gitlab-volume
              subPath: config/ssl
            - mountPath: /var/run/docker.sock
              name: dockersock
          ports:
            - containerPort: 443
      volumes:
        - name: gitlab-volume
          persistentVolumeClaim:
            claimName: gitlab-pvc
        - name: dockersock
          hostPath:
            path: /var/run/docker.sock
      hostname: gitlab-runner-smartclide
      restartPolicy: Always
