#*******************************************************************************
# Copyright (C) 2021-2022 AIR Institute
# 
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
# 
# SPDX-License-Identifier: EPL-2.0
# 
# Contributors:
#    avraampiperidis- initial API and implementation
#*******************************************************************************

# This is a kubernetes configuration file describing
# how we want to have a gitlab deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab-deployment
  labels:
    app: gitlab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitlab
  template:
    metadata:
      labels:
        app: gitlab
    spec:
      containers:
        - name: gitlab
          image: gitlab/gitlab-ee:latest          
          env:
            - name: GITLAB_OMNIBUS_CONFIG
              value: |
                  external_url 'https://localhost'
                  registry_external_url 'https://localhost:5050'
                  gitlab_rails['gitlab_shell_ssh_port'] = 22
          ports:
            - containerPort: 80
            - containerPort: 443
            - containerPort: 22
            - containerPort: 5050
          volumeMounts:
            - mountPath: /etc/gitlab
              name: gitlab-volume
              subPath: config
            - mountPath: /var/log/gitlab
              name: gitlab-volume
              subPath: logs
            - mountPath: /var/opt/gitlab
              name: gitlab-volume
              subPath: data
      volumes:
        - name: gitlab-volume
          persistentVolumeClaim:
            claimName: gitlab-pvc
      hostname: gitlab-smartclide
      restartPolicy: Always
